create table Curb
(
    id             int8 generated by default as identity,
    conditionIndex float8,
    length         float8,
    "order"        int4,
    segment_id     int8,
    state_id       int2,
    primary key (id)
)
;

create table Feature
(
    id   int2 generated by default as identity,
    name varchar(30) not null,
    primary key (id)
)
;

create table Nomenclature
(
    segment_id           int8 not null,
    crossFromNumber      varchar(255),
    crossUpNumber        varchar(255),
    generatingPathNumber varchar(255),
    crossFrom_id         int2,
    crossUp_id           int2,
    generatingPath_id    int2,
    primary key (segment_id)
)
;

create table RoadType
(
    id   int2 generated by default as identity,
    name varchar(30) not null,
    primary key (id)
)
;

create table Roadway
(
    id         int8 generated by default as identity,
    iri        float8,
    mdr        float8,
    opi        float8,
    feature_id int2,
    segment_id int8,
    surface_id int2,
    primary key (id)
)
;

create table Segment
(
    id          int8 not null,
    length      float8,
    stratum     int2,
    roadType_id int2 not null,
    primary key (id)
)
;

create table State
(
    id   int2 generated by default as identity,
    name varchar(30) not null,
    primary key (id)
)
;

create table Surface
(
    id   int2 generated by default as identity,
    name varchar(30) not null,
    primary key (id)
)
;

alter table if exists Curb
    add constraint FKahglehxul1wh18n4qoro19vag
        foreign key (segment_id)
            references Segment
;

alter table if exists Curb
    add constraint FKnnf807r1k50pb80lwqsrwumlj
        foreign key (state_id)
            references State
;

alter table if exists Nomenclature
    add constraint FK702rsx2mrbdnv30qah8fmnl1w
        foreign key (crossFrom_id)
            references RoadType
;

alter table if exists Nomenclature
    add constraint FKst9i2hf0dbg7fe7wq99lv25h3
        foreign key (crossUp_id)
            references RoadType
;

alter table if exists Nomenclature
    add constraint FKb0r60ii9hwi5ariy06yv1g23i
        foreign key (generatingPath_id)
            references RoadType
;

alter table if exists Nomenclature
    add constraint FKrugk0fwp9r7jcg4ei7vffyfoj
        foreign key (segment_id)
            references Segment
;

alter table if exists Roadway
    add constraint FK6diawi0pmvhnaqklkms2dcrw8
        foreign key (feature_id)
            references Feature
;

alter table if exists Roadway
    add constraint FKa4yq9sfcs239l6gwkuq0mlq6s
        foreign key (segment_id)
            references Segment
;

alter table if exists Roadway
    add constraint FKcai0l75st7cu6lkocd4cn6amh
        foreign key (surface_id)
            references Surface
;

alter table if exists Segment
    add constraint FKgjf1aq1p1ml87tkjcra4vqdq
        foreign key (roadType_id)
            references RoadType;